USE chat_db;

CREATE TABLE User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Message (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  sentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  sent_by INT,
  FOREIGN KEY (sent_by) REFERENCES User(id)
) ENGINE=InnoDB;